version: '2'
services:

  php:
    image: kashifz/php-fpm-laravel-mysql-redis:7.4
    volumes:
      - ./:/var/www/
      - $HOME/.composer/:$HOME/.composer/
    environment:
      - "DB_HOST=mysql"
      - "DB_DATABASE=homestead"
      - "DB_USERNAME=homestead"
      - "DB_PASSWORD=homestead"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"

  mysql:
    image: mysql:5.7
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=homestead"

  redis:
    image: redis:4.0-alpine
    command: redis-server --appendonly yes

volumes:
  mysqldata:
